# study in lasso

In [1]:
from sklearn.datasets import make_regression

In [24]:
from sklearn.datasets import load_boston
from sklearn.utils import shuffle
from sklearn import linear_model
from sklearn.model_selection import cross_val_score, RepeatedKFold
from skopt import BayesSearchCV

In [8]:
boston = load_boston()

In [9]:
X, y = shuffle(boston.data, boston.target, random_state=13)

In [12]:
reg = linear_model.Lasso(alpha=0.1)

In [29]:
%%time
if True:
    # Set to True if we want to run the BayesSearchCV process
    params = {'alpha': (0.0001,10)}

    optimiser = BayesSearchCV(reg, params, n_jobs=-1, n_iter=50, cv=RepeatedKFold(n_repeats=5))
    #opt = BayesSearchCV( SVC(), { 'C': Real(1e-6, 1e+6, prior='log-uniform'), 'gamma': Real(1e-6, 1e+1, prior='log-uniform'), 'degree': Integer(1,8), 'kernel': Categorical(['linear', 'poly', 'rbf']), }, n_iter=32 )
    #executes bayesian optimization

    # note we're fitting on all the data, so we're optimising wrt to the test data (might be silly)
    optimiser.fit(X, y)

    print(optimiser.score(X, y), optimiser.best_params_)
    #pd.DataFrame(optimiser.cv_results_)

/opt/conda/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:399: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
/opt/conda/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:399: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
/opt/conda/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:399: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
/opt/conda/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:399: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
/opt/conda/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:399: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "
/opt/conda/lib/python3.6/site-packa

0.7406426206930037 {'alpha': 0.0001}
CPU times: user 1min 29s, sys: 2.38 s, total: 1min 31s
Wall time: 32.9 s


In [13]:
reg.fit(X, y)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [ ]:
from sklearn.model_selection import 

In [22]:
scores = cross_val_score(reg, 
                         X, y, 
                         cv=RepeatedKFold(n_repeats=50), 
                         scoring=None) 

In [23]:
scores

array([0.72249392, 0.72058049, 0.67515424, 0.65345698, 0.77069053,
       0.60776792, 0.69522685, 0.80035215, 0.71231319, 0.58369343,
       0.6332168 , 0.70986818, 0.7160302 , 0.6842893 , 0.76108948,
       0.71947939, 0.58005628, 0.75636689, 0.72864248, 0.70446775,
       0.67545046, 0.74407106, 0.76356222, 0.75279732, 0.64152284,
       0.79945549, 0.76970771, 0.66028435, 0.75548356, 0.51020518,
       0.63762234, 0.7330666 , 0.69732273, 0.70857861, 0.76588775,
       0.74330731, 0.55030178, 0.7756624 , 0.69056645, 0.71300812,
       0.78163252, 0.77665242, 0.73147031, 0.47522991, 0.67021917,
       0.75763865, 0.68146271, 0.61173694, 0.73487249, 0.66867348,
       0.75106362, 0.74705305, 0.73108196, 0.66089508, 0.63060888,
       0.65811372, 0.71347412, 0.72078468, 0.65993902, 0.79250413,
       0.70982495, 0.70884386, 0.7201533 , 0.70600777, 0.63012302,
       0.63713318, 0.67884599, 0.8067276 , 0.71041515, 0.72335074,
       0.53529192, 0.6029808 , 0.7657159 , 0.78405395, 0.75358

In [51]:
import numpy as np
def make_regression_interaction(n_noise=10, n_informative=10, n_samples=500, interactions=[(10,11), (12,13)]):
    size = (500, n_noise + n_informative)
    draw = np.random.normal(size=size)
    int_mat = np.zeros((n_samples, len(interactions)))
    for i, locs in enumerate(interactions):
        int_mat[:,i] = draw[:,locs[0]] * draw[:, locs[1]]

    X = np.hstack([draw, int_mat])
    coefs = np.random.normal(size=n_noise + n_informative + len(interactions))
    coefs[:n_noise] = 0
    y = np.dot(X, coefs)
    return X, y, coefs
        

In [52]:
X, y, true_coefs = make_regression_interaction()

In [53]:
X.shape

(500, 22)

In [54]:
y.shape

(500,)

In [55]:
true_coefs

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.32705405,  0.60971445,  0.7998964 , -0.91425842,  0.01634442,
        1.05417015,  0.66081719, -0.28788392,  2.02153814, -0.46540406,
       -0.80757082, -1.67809217])

In [71]:
reg = linear_model.Lasso(alpha=0.01)

In [72]:
reg.fit(X, y)

Lasso(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [73]:
reg.coef_

array([-0.        ,  0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        , -0.        , -0.        ,  0.        ,
        0.31983329,  0.59830954,  0.78912013, -0.90696491,  0.00535545,
        1.04176674,  0.65444073, -0.27681124,  2.00949251, -0.45510983,
       -0.79757362, -1.66638592])