In [8]:
import numpy as np
import pandas as pd

In [11]:
train = pd.read_csv("train.csv")

In [14]:
train[['Age']].fillna(train.Age.mean(), inplace=True)
train[['Pclass']].fillna(train.Pclass.mean(), inplace=True)

In [15]:
train.drop("Cabin",inplace=True,axis=1)

In [16]:
train.dropna(inplace=True)

In [18]:
sex = pd.get_dummies(train["Sex"],drop_first=True)
embarked = pd.get_dummies(train["Embarked"],drop_first=True)
pclass = pd.get_dummies(train["Pclass"],drop_first=True)

In [19]:
train = pd.concat([train,pclass,sex,embarked],axis=1)

In [20]:
train.drop(["PassengerId","Pclass","Name","Sex","Ticket","Embarked"],axis=1,inplace=True)

In [21]:
X = train.drop("Survived",axis=1)
y = train["Survived"]

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 101)

In [24]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
predictions = logmodel.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.80      0.84      0.82       128
           1       0.74      0.70      0.72        86

   micro avg       0.78      0.78      0.78       214
   macro avg       0.77      0.77      0.77       214
weighted avg       0.78      0.78      0.78       214



In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[107,  21],
       [ 26,  60]])

# VW version

In [27]:
from vowpalwabbit.sklearn_vw import VWClassifier

In [45]:
# vw requires {+1,-1} for input data!
train['Survived'] = train['Survived'].map({1: 1, 0: -1})

In [46]:
X = train.drop("Survived",axis=1)
y = train["Survived"]

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 101)

In [74]:
model = VWClassifier(loss_function='logistic', link='logistic', convert_to_vw=True)
model.fit(X_train, y_train)

{'quiet': True, 'link': 'logistic', 'loss_function': 'logistic'}

In [75]:
??VWClassifier

In [76]:
predictions = model.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00      1015
         1.0       0.49      1.00      0.66       985

   micro avg       0.49      0.49      0.49      2000
   macro avg       0.25      0.50      0.33      2000
weighted avg       0.24      0.49      0.33      2000



/opt/conda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [58]:
model.decision_function(X_test)

array([0.12423094, 0.25162295, 0.64815784, 0.14973623, 0.12362408,
       0.12415335, 0.44522566, 0.44779125, 0.68772942, 0.14583515,
       0.17864318, 0.50195384, 0.44544691, 0.57823026, 0.74179959,
       0.12390354, 0.2243094 , 0.12320259, 0.12388254, 0.44680718,
       0.26820895, 0.33443668, 0.14063697, 0.62826377, 0.22965927,
       0.50346828, 0.48044318, 0.14962368, 0.44849795, 0.26814157,
       0.65122521, 0.77636963, 0.12334119, 0.50165135, 0.26297376,
       0.2267397 , 0.65316325, 0.33865812, 0.28503555, 0.69031906,
       0.72231436, 0.24867713, 0.1106369 , 0.1348743 , 0.12436007,
       0.26804549, 0.12111377, 0.62469631, 0.22568081, 0.14611416,
       0.12499657, 0.67572641, 0.32461175, 0.12429279, 0.44320431,
       0.12410071, 0.75641769, 0.12405992, 0.65592659, 0.12347862,
       0.12490128, 0.13860182, 0.44582352, 0.12403497, 0.69659501,
       0.1242573 , 0.62412882, 0.62881762, 0.12311032, 0.14160031,
       0.70086938, 0.14519574, 0.25341967, 0.28541306, 0.32320

In [72]:
from vowpalwabbit.sklearn_vw import VWClassifier

import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

# get some data
X, y = datasets.make_hastie_10_2(n_samples=10000, random_state=1)
X = X.astype(np.float32)

# split train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=256)

# build vowpal wabbit model
model = VWClassifier(loss_function='logistic', link='logistic')
model.fit(X_train, y_train)


{'quiet': True, 'link': 'logistic', 'loss_function': 'logistic'}

In [73]:
model.predict(X_test).mean()

1.0

In [67]:
from vowpalwabbit.sklearn_vw import VWClassifier

import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

# get some data
X, y = datasets.make_hastie_10_2(n_samples=10000, random_state=1)
X = X.astype(np.float32)

# split train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=256)

# build vowpal wabbit model
model = VWClassifier()
model.fit(X_train, y_train)

{'quiet': True, 'loss_function': 'logistic'}

In [71]:
model.predict(X_train)

array([ 1.,  1.,  1., ...,  1., -1.,  1.])

In [79]:
!pip install --user git+https://github.com/coreylynch/pyFM

  Cloning https://github.com/coreylynch/pyFM to /tmp/pip-req-build-zq1xj3dj
  Running command git clone -q https://github.com/coreylynch/pyFM /tmp/pip-req-build-zq1xj3dj
  Created wheel for pyfm: filename=pyfm-0.0.0-cp36-cp36m-linux_x86_64.whl size=232327 sha256=013b9499ece74325c261fa9c2a55f84a95edbd63d4d1bb5bf06bff404f4c0457
  Stored in directory: /tmp/pip-ephem-wheel-cache-139pphx1/wheels/3b/d9/ef/1b148c527d39344632833679e79b3db1798a40b0f64f917b13
Successfully built pyfm


In [80]:
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split
from pyfm import pylibfm

from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000,n_features=100, n_clusters_per_class=1)
data = [ {v: k for k, v in dict(zip(i, range(len(i)))).items()}  for i in X]

X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.1, random_state=42)

v = DictVectorizer()
X_train = v.fit_transform(X_train)
X_test = v.transform(X_test)

fm = pylibfm.FM(num_factors=50, num_iter=10, verbose=True, task="classification", initial_learning_rate=0.0001, learning_rate_schedule="optimal")

fm.fit(X_train,y_train)


Creating validation dataset of 0.01 of training for adaptive regularization
-- Epoch 1
Training log loss: 2.04571
-- Epoch 2
Training log loss: 1.77167
-- Epoch 3
Training log loss: 1.53345
-- Epoch 4
Training log loss: 1.32768
-- Epoch 5
Training log loss: 1.15034
-- Epoch 6
Training log loss: 0.99773
-- Epoch 7
Training log loss: 0.86666
-- Epoch 8
Training log loss: 0.75433
-- Epoch 9
Training log loss: 0.65825
-- Epoch 10
Training log loss: 0.57632
