In [1]:
using Pkg
using Test

In [2]:
Pkg.installed()

Dict{String,Union{Nothing, VersionNumber}} with 3 entries:
  "HDF5"   => v"0.12.5"
  "IJulia" => v"1.20.2"
  "Flux"   => v"0.10.0"

In [3]:
@test 1==1

Test Passed

In [4]:
]

In [15]:
println("Hello World!")

Hello World!


In [16]:
3+3

6

In [18]:
s1 = "hello"

"hello"

In [21]:
s1[1]    # Julia is 1-indexed!

'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)

In [23]:
name = "Jonathan";

In [31]:
println("Hello $name.")

Hello Jonathan.


In [34]:
s1 * " " * name

"hello Jonathan"

In [38]:
my_phonebook = Dict(Jenny->"867-5309", Ghostbusters->"2222")

MethodError: MethodError: no method matching Dict(::getfield(Main, Symbol("##8#10")), ::getfield(Main, Symbol("##9#11")))
Closest candidates are:
  Dict(::Any) at dict.jl:127

In [39]:
using Printf
using Statistics

In [40]:
function changeNum()
    x::Int8 = 10
    x = "Dog"
end

changeNum (generic function with 1 method)

In [49]:
a1 = zeros(Int32, 10, 10)

10×10 Array{Int32,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [6]:
using Distributed

In [9]:
nprocs()

3

In [8]:
addprocs(2)

2-element Array{Int64,1}:
 2
 3

In [10]:
for pid in workers()
    println(pid)
end

2
3


# Julia Iris

In [182]:
versioninfo()

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_DEPOT_PATH = /opt/julia
  JULIA_VERSION = 1.2.0
  JULIA_PKGDIR = /opt/julia


In [183]:
JULIA_CUDA_SILENT = true   # Turn off notifications about GPU/CUDA; doesn't seem to work (?)

true

In [255]:
using Pkg
Pkg.add("ProgressMeter")

  Updating registry at `/opt/julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 %]  42.1 % [==================================>      ]  84.6 % Resolving package versions...
 Installed FixedPointNumbers ─ v0.6.1
 Installed ProgressMeter ───── v1.2.0
  Updating `/opt/julia/environments/v1.2/Project.toml`
  [92933f4c] + ProgressMeter v1.2.0
  Updating `/opt/julia/environments/v1.2/Manifest.toml`
  [53c48c17] ↓ FixedPointNumbers v0.7.0 ⇒ v0.6.1
  [92933f4c] + ProgressMeter v1.2.0


In [256]:
using Flux
using Flux: crossentropy, normalise, onecold, onehotbatch
using ProgressMeter
using Random
using Statistics: mean

┌ Info: Precompiling ProgressMeter [92933f4c-e287-5a05-a399-4b506db050ca]
└ @ Base loading.jl:1242


In [262]:
pkgs = Pkg.installed()

Dict{String,Union{Nothing, VersionNumber}} with 4 entries:
  "HDF5"          => v"0.12.5"
  "IJulia"        => v"1.20.2"
  "Flux"          => v"0.10.0"
  "ProgressMeter" => v"1.2.0"

In [185]:
labels = Flux.Data.Iris.labels()
features = Flux.Data.Iris.features();

In [186]:
# note features is features x samples (opposite of usual)

labels[1:5], features[:, 1:5]

(["Iris-setosa", "Iris-setosa", "Iris-setosa", "Iris-setosa", "Iris-setosa"], [5.1 4.9 … 4.6 5.0; 3.5 3.0 … 3.1 3.6; 1.4 1.4 … 1.5 1.4; 0.2 0.2 … 0.2 0.2])

In [187]:
# Subract mean, divide by std dev for normed mean of 0 and std dev of 1.
normed_features = normalise(features, dims=2)   # 2 means rowwise

4×150 Array{Float64,2}:
 -0.900681  -1.14302   -1.38535   …   0.795669  0.432165   0.0686618
  1.03206   -0.124958   0.337848     -0.124958  0.800654  -0.124958 
 -1.34127   -1.34127   -1.39814       0.819624  0.933356   0.762759 
 -1.31298   -1.31298   -1.31298       1.05354   1.44796    0.790591 

In [188]:
?onehotbatch

search:



```
onehotbatch(ls, labels[, unk...])
```

Create an [`OneHotMatrix`](@ref) with a batch of labels based on possible `labels` set, returns the `onehot(unk, labels)` if given labels `ls` is not found in set `labels`.

## Examples

```jldoctest
julia> using Flux: onehotbatch

julia> onehotbatch([:b, :a, :b], [:a, :b, :c])
3×3 Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}:
 0  1  0
 1  0  1
 0  0  0
```


In [189]:
klasses = sort(unique(labels))
onehot_labels = onehotbatch(labels, klasses)

3×150 Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  1  1  1  1  1  1  1  1  1  1

In [190]:
klasses

3-element Array{String,1}:
 "Iris-setosa"    
 "Iris-versicolor"
 "Iris-virginica" 

In [191]:
onehot_labels

3×150 Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  1  1  1  1  1  1  1  1  1  1

In [192]:
# Split into training and test sets, 2/3 for training, 1/3 for test.
# start:step:end and the ; means to concatenate the two
# train_indices = [1:3:150 ; 2:3:150];

In [193]:
# this is more like the sklearn way
idxs = randperm(length(labels))
train_cut = Int(length(labels) * 0.66)
train_indices = idxs[1:train_cut]
test_indices = idxs[train_cut:length(labels)];

In [194]:
X_train = normed_features[:, train_indices]
y_train = onehot_labels[:, train_indices]

X_test = normed_features[:, test_indices]
y_test = onehot_labels[:, test_indices];

In [195]:
?Chain

search: Chain



```
Chain(layers...)
```

Chain multiple layers / functions together, so that they are called in sequence on a given input.

```julia
m = Chain(x -> x^2, x -> x+1)
m(5) == 26

m = Chain(Dense(10, 5), Dense(5, 2))
x = rand(10)
m(x) == m[2](m[1](x))
```

`Chain` also supports indexing and slicing, e.g. `m[2]` or `m[1:end-1]`. `m[1:3](x)` will calculate the output of the first three layers.


In [157]:
?Dense

search: Dense DenseArray DenseVector DenseMatrix DenseVecOrMat DenseConvDims



```
Dense(in::Integer, out::Integer, σ = identity)
```

Creates a traditional `Dense` layer with parameters `W` and `b`.

```
y = σ.(W * x .+ b)
```

The input `x` must be a vector of length `in`, or a batch of vectors represented as an `in × N` matrix. The out `y` will be a vector or batch of length `out`.

```julia
julia> d = Dense(5, 2)
Dense(5, 2)

julia> d(rand(5))
Tracked 2-element Array{Float64,1}:
  0.00257447
  -0.00449443
```


In [233]:
# The dense layer is just a matrix multiply; it has param W with shape (NxM); input is M, output is N
# This is 4 inputs to three neurons; there is a bias which is an integer
# Note the .+ to indicate broadcasting
x = [5, 1, 4, 6]
b = 0.25
W = Dense(4,3).W

3×4 Array{Float32,2}:
  0.775586  -0.304971   0.421589   -0.436464
 -0.323282  -0.164366   0.0802988  -0.390513
  0.347033  -0.63944   -0.0454182  -0.369854

In [230]:
?identity

search: identity



```
identity(x)
```

The identity function. Returns its argument.

# Examples

```jldoctest
julia> identity("Well, what did you expect?")
"Well, what did you expect?"
```


In [232]:
W*x .+ b

3-element Array{Float64,1}:
 4.041679382324219 
 0.5067691802978516
 8.800432205200195 

In [168]:
# Declare model taking 4 features as inputs and outputting 3 probabiltiies, 
# one for each species of iris.
model = Chain(
    Dense(4, 3),
    softmax
)

Chain(Dense(4, 3), softmax)

In [223]:
model.layers

(Dense(4, 3), NNlib.softmax)

In [228]:
# get the parameters of the first layer
params(model[1])

Params([Float32[-1.4777225 1.6287514 -2.0652995 -2.1090415; 0.5130562 -0.70725 -0.4703287 -0.9004947; 0.3975363 -0.8862645 2.6626518 2.6652656], Float32[-0.34812948, 2.2498853, -1.901755]])

In [222]:
# Chain means a function that applies step wise functions

In [221]:
?softmax

search: softmax softmax! ∇softmax ∇softmax! logsoftmax logsoftmax! ∇logsoftmax



```
softmax(xs) = exp.(xs) ./ sum(exp.(xs))
```

[Softmax](https://en.wikipedia.org/wiki/Softmax_function) takes log-probabilities (any real vector) and returns a probability distribution that sums to 1.

If given a matrix it will treat it as a batch of vectors, with each column independent.

```
julia> softmax([1,2,3.])
3-element Array{Float64,1}:
  0.0900306
  0.244728
  0.665241
```


In [169]:
loss(x, y) = crossentropy(model(x), y)

# Gradient descent optimiser with learning rate 0.5.
optimiser = Descent(0.5)

Descent(0.5)

In [235]:
?Descent

search: Descent



Descent(η)

Classic gradient descent optimiser with learning rate `η`. For each parameter `p` and its gradient `δp`, this runs `p -= η*δp`

## Parameters

  * Learning Rate (η): The amount by which the gradients are discounted before updating the weights. Defaults to `0.1`.

## Example

```julia-repl
opt = Descent() # uses default η (0.1)

opt = Descent(0.3) # use provided η

ps = params(model)

gs = gradient(ps) do
  loss(x, y)
end

Flux.Optimise.update!(opt, ps, gs)
```


In [175]:
# Create iterator to train model over 110 epochs.
data_iterator = Iterators.repeated((X_train, y_train), 150)

Base.Iterators.Take{Base.Iterators.Repeated{Tuple{Array{Float64,2},Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}}}}(Base.Iterators.Repeated{Tuple{Array{Float64,2},Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}}}(([0.5533332750260047 -0.9006811702978109 … -0.05250607719225172 -0.5371775589668563; -1.281972426831577 1.0320572244889543 … -0.5877635314354182 0.800654259356901; 0.705892938853251 -1.3412724047598341 … 0.7627586428425032 -1.2844067007705817; 0.9220637630692059 -1.3129767272601456 … 1.579428613166074 -1.0500307872213983], Bool[0 1 … 0 1; 0 0 … 0 0; 1 0 … 1 0])), 150)

In [241]:
?Iterators.repeated

```
repeated(x[, n::Int])
```

An iterator that generates the value `x` forever. If `n` is specified, generates `x` that many times (equivalent to `take(repeated(x), n)`).

# Examples

```jldoctest
julia> a = Iterators.repeated([1 2], 4);

julia> collect(a)
4-element Array{Array{Int64,2},1}:
 [1 2]
 [1 2]
 [1 2]
 [1 2]
```


In [242]:
?Flux.train!

```
train!(loss, params, data, opt; cb)
```

For each datapoint `d` in `data` computes the gradient of `loss(d...)` through backpropagation and calls the optimizer `opt`.

Takes a callback as keyword argument `cb`. For example, this will print "training" every 10 seconds:

```julia
Flux.train!(loss, params, data, opt,
            cb = throttle(() -> println("training"), 10))
```

The callback can call `Flux.stop()` to interrupt the training loop.

Multiple optimisers and callbacks can be passed to `opt` and `cb` as arrays.


In [259]:
@time Flux.train!(loss, params(model), data_iterator, optimiser)
@info "Training done..."

  0.026197 seconds (458.13 k allocations: 11.549 MiB)


┌ Info: Training done...
└ @ Main In[259]:2


In [245]:
?onecold

search: SkipConnection ExponentialBackOff



```
onecold(y[, labels = 1:length(y)])
```

Inverse operations of [`onehot`](@ref).

```jldoctest
julia> using Flux: onecold

julia> onecold([true, false, false], [:a, :b, :c])
:a

julia> onecold([0.3, 0.2, 0.5], [:a, :b, :c])
:c
```


In [247]:
#onecold is like argmax
onecold(model(X_test))

52-element Array{Int64,1}:
 2
 3
 3
 2
 2
 1
 2
 1
 1
 1
 1
 1
 2
 ⋮
 1
 3
 3
 3
 3
 2
 1
 1
 3
 3
 3
 3

In [248]:
y_test

3×52 Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}:
 0  0  0  0  0  1  0  1  1  1  1  1  0  …  1  0  0  0  0  0  1  1  0  0  0  0
 1  0  0  1  0  0  1  0  0  0  0  0  1     0  0  0  0  0  1  0  0  0  0  0  0
 0  1  1  0  1  0  0  0  0  0  0  0  0     0  1  1  1  1  0  0  0  1  1  1  1

In [177]:
# Evaluate trained model against test set.
accuracy(x, y) = mean(onecold(model(x)) .== onecold(y))

accuracy (generic function with 1 method)

In [178]:
@time accuracy_score = accuracy(X_test, y_test)

  0.005635 seconds (2.87 k allocations: 138.418 KiB)


0.9230769230769231

In [179]:
function confusion_matrix(X, y)
    ŷ = onehotbatch(onecold(model(X)), 1:3)
    y * ŷ'
end

confusion_matrix (generic function with 1 method)

In [180]:
display(confusion_matrix(X_test, y_test))

3×3 Array{Int64,2}:
 16   0   0
  0  15   2
  0   2  17